name: Build CV (Pandoc)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure docs directory and .nojekyll
        run: |
          mkdir -p docs
          touch docs/.nojekyll

      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Setup Python and pypandoc
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install pypandoc

      - name: Render CV → docs/index.html
        run: |
          if [ -f "csl/ieee.csl" ]; then CSL="--csl=csl/ieee.csl"; else CSL=""; fi
          pandoc cv.md \
            --from markdown \
            --to html5 \
            --standalone \
            --metadata title="CV" \
            --citeproc \
            --bibliography=publications.bib \
            --csl=csl/chicago-author-date-date-desc.csl \
            --output docs/index.html

      - name: Commit rendered HTML
        run: |
          if ! git diff --quiet -- docs/index.html; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs/index.html docs/.nojekyll
            git commit -m "chore: update CV build [skip ci]"
            git push
          fi
