name: Build CV (Pandoc)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure docs directory and .nojekyll
        run: |
          mkdir -p docs
          touch docs/.nojekyll

      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Render CV → docs/index.html
        run: |
          pandoc cv.md \
            --from markdown+fenced_divs \
            --to html5 \
            --standalone \
            --citeproc \
            --bibliography=publications.bib \
            --csl=csl/chicago-author-date-date-desc.csl \
            --template=templates/cv.html \
            --css=cv.css \
            --output docs/index.html
          cp css/cv.css docs/cv.css

      - name: Commit rendered HTML
        run: |
          if [[ -n "$(git status --short docs/index.html docs/.nojekyll)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs/index.html docs/cv.css docs/.nojekyll
            git commit -m "chore: update CV build [skip ci]"
            git push
          fi
